# Generated by Django 4.1.7 on 2023-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sperma", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Purchase",
            },
        ),
    ]
