# Generated by Django 4.1.7 on 2023-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatransfer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
